# Generated by Django 5.0.7 on 2024-08-16 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('subgrantees', '0014_alter_subgranteeprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='subgranteeprofile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='subgrantees.subgranteeprofile'),
        ),
    ]
