# Generated by Django 5.0.7 on 2024-10-15 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_ldapuser_distinguished_name_ldapuser_last_sync_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ldapuser',
            name='email',
            field=models.EmailField(default=True, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ldapuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='ldapuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
