# Generated by Django 5.0.7 on 2024-10-15 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_ldapuser_email_ldapuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ldap_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.ldapuser'),
        ),
        migrations.AlterField(
            model_name='ldapuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ldap_details', to=settings.AUTH_USER_MODEL),
        ),
    ]
