# Generated by Django 5.0.7 on 2024-10-15 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_customuser_ldap_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='ldap_user',
        ),
        migrations.AlterField(
            model_name='ldapuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ldap_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
