# Generated by Django 5.0.7 on 2024-10-15 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_remove_customuser_ldap_user_alter_ldapuser_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ldapuser',
            name='user',
        ),
    ]
