# Generated by Django 5.0.7 on 2024-10-16 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_remove_ldapuser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_ldap_user',
            field=models.BooleanField(default=False),
        ),
    ]
