# Generated by Django 5.0.7 on 2024-10-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_customuser_is_ldap_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ldapuser',
            old_name='distinguished_name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='ldapuser',
            name='last_sync',
        ),
        migrations.RemoveField(
            model_name='ldapuser',
            name='ldap_username',
        ),
        migrations.AddField(
            model_name='ldapuser',
            name='department',
            field=models.CharField(default=True, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ldapuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='ldapuser',
            name='first_name',
            field=models.CharField(default=True, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ldapuser',
            name='last_name',
            field=models.CharField(default=True, max_length=255),
            preserve_default=False,
        ),
    ]
