# Generated by Django 5.0.7 on 2024-10-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_rename_distinguished_name_ldapuser_username_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ldapuser',
            old_name='username',
            new_name='distinguished_name',
        ),
        migrations.RemoveField(
            model_name='ldapuser',
            name='department',
        ),
        migrations.AddField(
            model_name='ldapuser',
            name='last_sync',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ldapuser',
            name='ldap_username',
            field=models.CharField(default=True, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ldapuser',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='ldapuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ldapuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
