# Generated by Django 5.0.7 on 2024-10-23 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_rename_username_ldapuser_distinguished_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ldapuser',
            old_name='distinguished_name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='ldapuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='ldapuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='ldapuser',
            name='ldap_username',
        ),
        migrations.AddField(
            model_name='ldapuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
