from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import GrantListCreateAPIView, GrantApplicationReviewDetailAPIView, get_review_for_application, review_financial_report, AllFinanceReportsView, ExtensionCreateView, ExtensionDetailView, get_all_budget_items, get_all_applications, total_disbursements, get_most_recent_progress_report, get_most_recent_report, GrantApplicationApproveCountView, GrantDetailAPIView, GrantTypeView, DonorAPIView, activegrant_count, DefaultApplicationQuestionAPIView, grant_list, GrantApplicationResponsesAPIView, GrantApplicationListCreateView, GrantApplicationDetailView, GrantApplicationDetailView, GrantApplicationReviewListCreateAPIView, get_transformed_data,  GrantApplicationDocumentUploadView, GrantApplicationDocumentListView, filtered_responses_view, UserApplicationDocumentsView, GrantAccountReportView, GrantAccountDetailView, BudgetItemListView, BudgetItemDetailView, FundingAllocationListView, FundingAllocationDetailView, BudgetCategoryListView, BudgetCategoryDetailView, update_grant, GrantApplicationCountView, get_pending_approval_applications_count, get_rejected_applications_count, get_report, generate_report, list_reports, ProgressReportView, AllProgressReportsView, review_progress_report, create_disbursement, get_all_accounts, get_disbursements, get_disbursements_by_account, update_disbursement, GrantCloseoutView, get_grant_application_details, get_all_grantcloseout_requests,  get_closeout_request_details, RequestsListCreateAPIView, create_or_update_closeout_request, get_all_requests, ModificationsView, GrantCloseOutReviewAPIView, signed_applications_percentage, RequirementsList, RequirementsDetail, RequestReviewCreateView, RequestReviewDetailView, GrantApplicationReviewDocumentUploadView

urlpatterns = [
    path("grants/", GrantListCreateAPIView.as_view(), name="grant-list-create"),
    path("grants/<int:pk>/", GrantDetailAPIView.as_view(), name="grant-detail"),
    path('grant-types/', GrantTypeView.as_view(), name='grant-type-list'),
    path('grant-types/<int:pk>/', GrantTypeView.as_view(),
         name='grant-type-detail'),
    path('donors/', DonorAPIView.as_view(), name='donor-list-create'),
    path('donors/<int:pk>/', DonorAPIView.as_view(), name='donor-detail'),
    path("active-count/", activegrant_count, name="active-grant-count"),
    path("questions/", DefaultApplicationQuestionAPIView.as_view(),
         name='question-list'),
    path("list/", grant_list, name='grant-list'),
    path("responses/", GrantApplicationResponsesAPIView.as_view(),
         name='grant-application-responses'),
    path("responses/<int:grant_id>/", GrantApplicationResponsesAPIView.as_view(),
         name='grant-application-responses'),
    path("applications/", GrantApplicationResponsesAPIView.as_view(),
         name='grant-applications-responses'),
    path('all-applications/', get_all_applications, name='all-apps'),
    path("grant-applications/",
         GrantApplicationListCreateView.as_view(), name='applications'),
    path("grant-applications/count/",
         GrantApplicationCountView.as_view(), name='applications-count'),
    path("grant-applications/approve/count/",
         GrantApplicationApproveCountView.as_view(), name='applications-approve-count'),
    path("grant-applications/pending/count/", get_pending_approval_applications_count,
         name='pending-approval-applications-count'),
    path("grant-applications/rejected/count/",
         get_rejected_applications_count, name='rejected-applications-count'),
    path("grant-applications/<int:user_id>/",
         GrantApplicationListCreateView.as_view(), name='applications'),
    path('grant-applications/<int:pk>/specific/',
         GrantApplicationDetailView.as_view(), name='application-detail'),
    path('reviews/', GrantApplicationReviewListCreateAPIView.as_view(),
         name='review-list-create'),
    path('reviews/<int:pk>/',
         GrantApplicationReviewListCreateAPIView.as_view(), name='review-update'),
    path('transformed-data/', get_transformed_data, name='get_transformed_data'),
    path('applications/<int:application_id>/documents/',
         GrantApplicationDocumentUploadView.as_view(), name='upload_documents'),
    path('applications/<int:application_id>/documents/list/',
         GrantApplicationDocumentListView.as_view(), name='list_documents'),
    path('applications/documents/', UserApplicationDocumentsView.as_view(),
         name='user-application-documents'),
    path('filtered-responses/', filtered_responses_view, name='filtered-responses'),
    path('grant_account/<int:account_id>/report/',
         GrantAccountReportView.as_view(), name='grant_account_report'),
    path('grant-account/<int:user_id>/',
         GrantAccountDetailView.as_view(), name='grant_account_detail'),
    path('budget_item/<int:user_id>/<int:category_id>/',
         BudgetItemListView.as_view(), name='budget_item_list'),
    path('budget_item/<int:user_id>/<int:category_id>/<int:pk>', BudgetItemDetailView.as_view(),
         name='budget_item_detail'),
    path('funding/<int:user_id>/allocations/',
         FundingAllocationListView.as_view(), name='funding-allocation-list'),
    path('funding/<int:user_id>/allocations/<int:pk>/',
         FundingAllocationDetailView.as_view(), name='funding_allocation_detail'),
    path('budget_category/<int:user_id>/', BudgetCategoryListView.as_view(),
         name='budget_category_list'),
    path('budget_category/<int:user_id>/<int:category_id>/',
         BudgetCategoryListView.as_view(), name='budget-category-detail'),
    path('budget_category/<int:pk>/<int:user_id>/', BudgetCategoryDetailView.as_view(),
         name='budget_category_detail'),
    path('report/<int:grant_account_id>/<str:report_date>/',
         get_report, name='get_report'),
    path('generate-report/<int:grant_account_id>/',
         generate_report, name='generate_report'),
    path('list_reports/', list_reports, name='list_reports'),
    path('progress-report/<int:grant_account_id>/',
         ProgressReportView.as_view(), name='progress_report'),
path('budget_item/<int:user_id>/', get_all_budget_items, name='budget_item_list'),
    path('progress-reports/', AllProgressReportsView.as_view(),
         name='all_progress_reports'),
    path('finance-reports/', AllFinanceReportsView.as_view(), name='all_finance_reports'),
    path('progress-reports/<int:report_id>/review/',
         review_progress_report, name='review-report'),
    path('finance-reports/<int:report_id>/review/', review_financial_report, name='review-financial-report'),     
    path('grant-accounts/', get_all_accounts, name='grant-accounts'),
    path('disbursements-all/', get_disbursements, name='disbursements'),
    path('disbursements-by-account/<int:account_id>/',
         get_disbursements_by_account, name='disbursements-by-account'),
    path('disbursements/<int:pk>/update/',
         update_disbursement, name='update-disbursement'),
    path('disbursements/create/<int:account_id>/',
         create_disbursement, name='create-disbursement'),
    path('grant-account/<int:grant_account_id>/closeout/',
         GrantCloseoutView.as_view(), name='grant-closeout'),
    path('grant-applications/<int:application_id>/',
         get_grant_application_details, name='get_grant_application_details'),
    path('grant-closeout-requests/',
         get_all_grantcloseout_requests, name='grant-closeouts'),
    path('grant-closeout-requests/<int:closeout_id>/',
         get_closeout_request_details, name='grant-closeout-request'),
    path('requests/<int:user_id>/', RequestsListCreateAPIView.as_view(),
         name='requests-list-create'),
    path('grant-closeout-request/', create_or_update_closeout_request, name='initiate-closeout'),
    path('all-requests/', get_all_requests, name='all-requests'),  
    path('modifications/', ModificationsView.as_view(), name='modifications'),   
    path('closeouts/<int:closeout_id>/reviews/',
         GrantCloseOutReviewAPIView.as_view(), name='grantcloseoutreview'),
    path('most-recent-financial-report/<int:grant_account_id>/', get_most_recent_report, name='most-recent-financial-report'),
    path('most-recent-progress-report/<int:grant_account_id>/', get_most_recent_progress_report, name='most-recent-progress-report'),
    path('signed-applications-percentage/', signed_applications_percentage, name='signed_applications_percentage'),
    path('total-disbursements/', total_disbursements, name='total_disbursements'),
    path('requirements/', RequirementsList.as_view(), name='requirements-list'),
    path('requirements/<int:pk>/', RequirementsDetail.as_view(),
         name='requirements-detail'),
    path('request-reviews/', RequestReviewCreateView.as_view(),
         name='request-review-create'),
    path('request-reviews/<int:pk>/', RequestReviewDetailView.as_view(),
         name='request-review-detail'),
    path('grant-extension/', ExtensionCreateView.as_view(), name='grant-extension'),
    path('grant-extension/<int:pk>/', ExtensionDetailView.as_view(), name='dets'),
    path('update-grant/<int:pk>/', update_grant), 
    path('review-upload/<int:review_id>/', GrantApplicationReviewDocumentUploadView.as_view(), name='uploads-review'),    
    path('review-application/<int:application_id>/', get_review_for_application),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
