# Generated by Django 5.0.7 on 2024-08-07 18:09

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grants_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.TextField()),
                ('meeting_frequency', models.CharField(max_length=255)),
                ('last_three_meetings', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('details', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CurrentProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor', models.CharField(max_length=255)),
                ('timeframe', models.CharField(max_length=255)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.TextField()),
                ('contact_info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialAndAdministrativeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accounting_system', models.CharField(max_length=255)),
                ('finance_admin_manual', models.BooleanField()),
                ('finance_admin_manual_updated_date', models.DateField(blank=True, null=True)),
                ('finance_admin_manual_reason', models.TextField(blank=True, null=True)),
                ('hr_manual', models.BooleanField()),
                ('hr_manual_updated_date', models.DateField(blank=True, null=True)),
                ('hr_manual_reason', models.TextField(blank=True, null=True)),
                ('anti_corruption_policy', models.BooleanField()),
                ('whistleblower_policy', models.BooleanField()),
                ('audits_in_last_three_years', models.BooleanField()),
                ('audit_details', models.TextField(blank=True, null=True)),
                ('audit_issues_and_actions', models.TextField(blank=True, null=True)),
                ('forensic_audit', models.BooleanField()),
                ('forensic_audit_details', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('programmatic_capacity', models.TextField()),
                ('financial_management_capacity', models.TextField()),
                ('administrative_management_capacity', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PastProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=15)),
                ('outcomes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StaffAndVolunteers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_male', models.PositiveIntegerField()),
                ('staff_female', models.PositiveIntegerField()),
                ('volunteers_male', models.PositiveIntegerField()),
                ('volunteers_female', models.PositiveIntegerField()),
                ('staff_dedicated_to_me', models.BooleanField(default=False)),
                ('me_responsibilities', models.TextField(blank=True, null=True)),
                ('me_coverage', models.TextField(blank=True, null=True)),
                ('gender_inclusion', models.TextField()),
                ('finance_manager', models.BooleanField(default=False)),
                ('finance_manager_details', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('duration', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SubgranteeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subgrantees.district')),
            ],
        ),
        migrations.CreateModel(
            name='AuditIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_date', models.DateField(default=datetime.date.today)),
                ('issue_raised', models.TextField()),
                ('action_taken', models.TextField()),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('financial_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_issues', to='subgrantees.financialandadministrativedetails')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subgrantees.region'),
        ),
        migrations.CreateModel(
            name='Subcounty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('county', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subgrantees.county')),
            ],
        ),
        migrations.CreateModel(
            name='SubgranteeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_address', models.TextField()),
                ('contact_person', models.CharField(max_length=255)),
                ('secondary_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('acronym', models.CharField(blank=True, max_length=50, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('executive_director_name', models.CharField(max_length=255)),
                ('executive_director_contact', models.CharField(max_length=255)),
                ('board_chair_name', models.CharField(max_length=255)),
                ('board_chair_contact', models.CharField(max_length=255)),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('most_recent_registration_date', models.DateField(default=django.utils.timezone.now)),
                ('registration_number', models.CharField(max_length=100)),
                ('has_mission_vision_values', models.BooleanField()),
                ('mission', models.TextField(blank=True, null=True)),
                ('vision', models.TextField(blank=True, null=True)),
                ('core_values', models.TextField(blank=True, null=True)),
                ('justification_for_partnership', models.TextField()),
                ('board_information', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subgrantee_profile', to='subgrantees.boardinformation')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subgrantee_profiles', to='subgrantees.subgranteecategory')),
                ('current_projects', models.ManyToManyField(blank=True, related_name='subgrantee_profiles', to='subgrantees.currentproject')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subgrantee_profiles', to='subgrantees.district')),
                ('financial_and_administrative_details', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subgrantee_profile', to='subgrantees.financialandadministrativedetails')),
                ('organization_description', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subgrantee_profile', to='subgrantees.organizationdescription')),
                ('partnerships', models.ManyToManyField(blank=True, related_name='subgrantee_profiles', to='subgrantees.partnership')),
                ('past_projects', models.ManyToManyField(blank=True, related_name='subgrantee_profiles', to='subgrantees.pastproject')),
                ('staff_and_volunteers', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_and_volunteers_profile', to='subgrantees.staffandvolunteers')),
                ('sub_grants', models.ManyToManyField(blank=True, related_name='subgrantee_profiles', to='subgrantees.subgrant')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='subgrant',
            name='subgrantee_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_grants_related', to='subgrantees.subgranteeprofile'),
        ),
        migrations.AddField(
            model_name='staffandvolunteers',
            name='subgrantee_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_and_volunteers_profile', to='subgrantees.subgranteeprofile'),
        ),
        migrations.AddField(
            model_name='pastproject',
            name='subgrantee_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='past_projects_related', to='subgrantees.subgranteeprofile'),
        ),
        migrations.AddField(
            model_name='partnership',
            name='subgrantee_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partnerships_related', to='subgrantees.subgranteeprofile'),
        ),
        migrations.AddField(
            model_name='currentproject',
            name='subgrantee_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_projects_related', to='subgrantees.subgranteeprofile'),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='grants_management.grantapplication')),
                ('contract_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='subgrantees.contracttype')),
                ('subgrantee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='subgrantees.subgranteeprofile')),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalSkillsAndCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_skills', models.TextField()),
                ('comparative_advantage', models.TextField()),
                ('monitoring_and_evaluation_capacity', models.TextField()),
                ('impact_determination', models.TextField()),
                ('external_evaluation_conducted', models.BooleanField(default=False)),
                ('external_evaluation_details', models.TextField(blank=True, null=True)),
                ('evaluation_use', models.TextField()),
                ('subgrantee_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technical_skills_profile', to='subgrantees.subgranteeprofile')),
            ],
        ),
        migrations.AddField(
            model_name='subgranteeprofile',
            name='technical_skills_and_capacity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technical_skills_profile', to='subgrantees.technicalskillsandcapacity'),
        ),
    ]
