# Generated by Django 5.0.7 on 2024-08-08 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subgrantees', '0002_remove_subgranteeprofile_justification_for_partnership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subgranteeprofile',
            name='board_information',
        ),
        migrations.AddField(
            model_name='subgranteeprofile',
            name='last_three_meetings_of_board',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subgranteeprofile',
            name='meeting_frequency_of_board',
            field=models.CharField(default=True, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subgranteeprofile',
            name='role_on_board',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staffandvolunteers',
            name='subgrantee_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_and_volunteers_profile', to='subgrantees.subgranteeprofile'),
        ),
        migrations.AlterField(
            model_name='subgranteeprofile',
            name='board_chair_contact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subgranteeprofile',
            name='board_chair_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subgranteeprofile',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subgranteeprofile',
            name='current_projects',
            field=models.ManyToManyField(blank=True, null=True, related_name='subgrantee_profiles', to='subgrantees.currentproject'),
        ),
        migrations.AlterField(
            model_name='subgranteeprofile',
            name='executive_director_contact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subgranteeprofile',
            name='executive_director_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subgranteeprofile',
            name='has_mission_vision_values',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subgranteeprofile',
            name='organisation_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subgranteeprofile',
            name='partnerships',
            field=models.ManyToManyField(blank=True, null=True, related_name='subgrantee_profiles', to='subgrantees.partnership'),
        ),
        migrations.AlterField(
            model_name='subgranteeprofile',
            name='past_projects',
            field=models.ManyToManyField(blank=True, null=True, related_name='subgrantee_profiles', to='subgrantees.pastproject'),
        ),
        migrations.AlterField(
            model_name='subgranteeprofile',
            name='registration_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subgranteeprofile',
            name='staff_and_volunteers',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_and_volunteers_profile', to='subgrantees.staffandvolunteers'),
        ),
        migrations.AlterField(
            model_name='subgranteeprofile',
            name='sub_grants',
            field=models.ManyToManyField(blank=True, null=True, related_name='subgrantee_profiles', to='subgrantees.subgrant'),
        ),
        migrations.AlterField(
            model_name='subgranteeprofile',
            name='user',
            field=models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BoardInformation',
        ),
    ]
