# Generated by Django 5.0.7 on 2024-08-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subgrantees', '0003_remove_subgranteeprofile_board_information_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subgranteeprofile',
            name='organization_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subgranteeprofile',
            name='organization_administrative_management_capacity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subgranteeprofile',
            name='organization_financial_management_capacity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subgranteeprofile',
            name='organization_programmatic_capacity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subgranteeprofile',
            name='last_three_meetings_of_board',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subgranteeprofile',
            name='meeting_frequency_of_board',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subgranteeprofile',
            name='role_on_board',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='OrganizationDescription',
        ),
    ]
