# Generated by Django 5.0.7 on 2024-08-08 16:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subgrantees', '0004_alter_subgranteeprofile_organization_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subgranteeprofile',
            name='financial_and_administrative_details',
        ),
        migrations.AddField(
            model_name='subgranteeprofile',
            name='audit_action_taken',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subgranteeprofile',
            name='audit_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='subgranteeprofile',
            name='audit_issue_raised',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subgranteeprofile',
            name='audit_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subgranteeprofile',
            name='finance_and_admin_dtl_accounting_system',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subgranteeprofile',
            name='finance_and_admin_dtl_anti_corruption_policy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subgranteeprofile',
            name='finance_and_admin_dtl_audit_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subgranteeprofile',
            name='finance_and_admin_dtl_audit_issues_and_actions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subgranteeprofile',
            name='finance_and_admin_dtl_audits_in_last_three_years',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subgranteeprofile',
            name='finance_and_admin_dtl_finance_admin_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subgranteeprofile',
            name='finance_and_admin_dtl_finance_admin_manual_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subgranteeprofile',
            name='finance_and_admin_dtl_finance_admin_manual_updated_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subgranteeprofile',
            name='finance_and_admin_dtl_forensic_audit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subgranteeprofile',
            name='finance_and_admin_dtl_forensic_audit_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subgranteeprofile',
            name='finance_and_admin_dtl_hr_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subgranteeprofile',
            name='finance_and_admin_dtl_hr_manual_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subgranteeprofile',
            name='finance_and_admin_dtl_hr_manual_updated_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subgranteeprofile',
            name='finance_and_admin_dtl_whistleblower_policy',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='AuditIssue',
        ),
        migrations.DeleteModel(
            name='FinancialAndAdministrativeDetails',
        ),
    ]
