# Generated by Django 5.0.7 on 2024-08-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subgrantees', '0005_remove_subgranteeprofile_financial_and_administrative_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subgranteeprofile',
            name='technical_skills_and_capacity',
        ),
        migrations.AddField(
            model_name='subgranteeprofile',
            name='technical_skills_comparative_advantage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subgranteeprofile',
            name='technical_skills_evaluation_use',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subgranteeprofile',
            name='technical_skills_external_evaluation_conducted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subgranteeprofile',
            name='technical_skills_external_evaluation_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subgranteeprofile',
            name='technical_skills_impact_determination',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subgranteeprofile',
            name='technical_skills_monitoring_and_evaluation_capacity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subgranteeprofile',
            name='technical_skills_technical_skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='TechnicalSkillsAndCapacity',
        ),
    ]
