# Generated by Django 5.0.7 on 2024-08-08 16:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subgrantees', '0006_remove_subgranteeprofile_technical_skills_and_capacity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subgranteeprofile',
            name='past_projects',
        ),
        migrations.RemoveField(
            model_name='staffandvolunteers',
            name='subgrantee_profile',
        ),
        migrations.RemoveField(
            model_name='subgranteeprofile',
            name='staff_and_volunteers',
        ),
        migrations.AddField(
            model_name='subgranteeprofile',
            name='finance_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subgranteeprofile',
            name='finance_manager_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subgranteeprofile',
            name='gender_inclusion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subgranteeprofile',
            name='me_coverage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subgranteeprofile',
            name='me_responsibilities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subgranteeprofile',
            name='past_project_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='subgranteeprofile',
            name='past_project_end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='subgranteeprofile',
            name='past_project_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subgranteeprofile',
            name='past_project_outcomes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subgranteeprofile',
            name='past_project_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subgranteeprofile',
            name='staff_dedicated_to_me',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subgranteeprofile',
            name='staff_female',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subgranteeprofile',
            name='staff_male',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subgranteeprofile',
            name='volunteers_female',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subgranteeprofile',
            name='volunteers_male',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='PastProject',
        ),
        migrations.DeleteModel(
            name='StaffAndVolunteers',
        ),
    ]
