# Generated by Django 5.0.7 on 2024-08-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subgrantees', '0007_remove_subgranteeprofile_past_projects_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subgranteeprofile',
            name='current_projects',
        ),
        migrations.RemoveField(
            model_name='partnership',
            name='subgrantee_profile',
        ),
        migrations.RemoveField(
            model_name='subgranteeprofile',
            name='partnerships',
        ),
        migrations.RemoveField(
            model_name='subgrant',
            name='subgrantee_profile',
        ),
        migrations.RemoveField(
            model_name='subgranteeprofile',
            name='sub_grants',
        ),
        migrations.AddField(
            model_name='subgranteeprofile',
            name='current_project_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='subgranteeprofile',
            name='current_project_contact_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subgranteeprofile',
            name='current_project_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subgranteeprofile',
            name='current_project_donor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subgranteeprofile',
            name='current_project_timeframe',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subgranteeprofile',
            name='partnership_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subgranteeprofile',
            name='partnership_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subgranteeprofile',
            name='partnership_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subgranteeprofile',
            name='partnership_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subgranteeprofile',
            name='partnership_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subgranteeprofile',
            name='subgrant_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='subgranteeprofile',
            name='subgrant_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subgranteeprofile',
            name='subgrant_donor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subgranteeprofile',
            name='subgrant_duration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='CurrentProject',
        ),
        migrations.DeleteModel(
            name='Partnership',
        ),
        migrations.DeleteModel(
            name='SubGrant',
        ),
    ]
