# Generated by Django 5.0.7 on 2024-08-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subgrantees', '0008_remove_subgranteeprofile_current_projects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subgranteeprofile',
            name='accounting_system',
            field=models.TextField(blank=True, null=True),
        ),
    ]
