# Generated by Django 5.0.7 on 2024-08-08 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subgrantees', '0009_subgranteeprofile_accounting_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subgranteeprofile',
            name='accounting_system',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
