# Generated by Django 5.0.7 on 2024-08-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subgrantees', '0010_alter_subgranteeprofile_accounting_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subgranteeprofile',
            name='finance_and_admin_dtl_accounting_system',
        ),
        migrations.RemoveField(
            model_name='subgranteeprofile',
            name='finance_and_admin_dtl_whistleblower_policy',
        ),
        migrations.AddField(
            model_name='subgranteeprofile',
            name='finance_and_admin_dtl_audit_details_not',
            field=models.TextField(blank=True, null=True),
        ),
    ]
