# Generated by Django 5.0.7 on 2024-08-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subgrantees', '0011_remove_subgranteeprofile_finance_and_admin_dtl_accounting_system_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subgranteeprofile',
            old_name='technical_skills_technical_skills',
            new_name='current_work_emphasizes',
        ),
        migrations.RenameField(
            model_name='subgranteeprofile',
            old_name='partnership_type',
            new_name='partnership_period',
        ),
        migrations.RemoveField(
            model_name='subgranteeprofile',
            name='partnership_end_date',
        ),
        migrations.RemoveField(
            model_name='subgranteeprofile',
            name='partnership_start_date',
        ),
        migrations.RemoveField(
            model_name='subgranteeprofile',
            name='past_project_end_date',
        ),
        migrations.RemoveField(
            model_name='subgranteeprofile',
            name='past_project_start_date',
        ),
        migrations.AddField(
            model_name='subgranteeprofile',
            name='past_project_contact_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subgranteeprofile',
            name='past_project_timeframe',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subgranteeprofile',
            name='technical_skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subgranteeprofile',
            name='technical_skills_external_evaluation_details_not',
            field=models.TextField(blank=True, null=True),
        ),
    ]
