# Generated by Django 5.0.7 on 2024-08-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subgrantees', '0012_rename_technical_skills_technical_skills_subgranteeprofile_current_work_emphasizes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subgranteeprofile',
            name='acronym',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
