# Generated by Django 5.0.7 on 2024-08-16 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subgrantees', '0013_alter_subgranteeprofile_acronym'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='subgranteeprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subgrantee_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
