# Generated by Django 5.0.7 on 2024-09-03 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants_management', '0103_rename_approved_date_grantcloseout_review_date'),
        ('subgrantees', '0014_alter_subgranteeprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subgranteeprofile',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grants_management.granttype'),
        ),
    ]
