# Generated by Django 5.0.7 on 2024-09-06 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subgrantees', '0016_alter_subgranteeprofile_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='subgranteeprofile',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
