# Generated by Django 5.0.7 on 2024-09-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subgrantees', '0017_subgranteeprofile_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='subgranteeprofile',
            name='current_projects_json',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='subgranteeprofile',
            name='past_projects_json',
            field=models.TextField(default='[]'),
        ),
    ]
