# Generated by Django 5.0.7 on 2024-09-16 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subgrantees', '0018_subgranteeprofile_current_projects_json_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subgranteeprofile',
            name='current_projects_json',
        ),
        migrations.RemoveField(
            model_name='subgranteeprofile',
            name='past_projects_json',
        ),
    ]
