# Generated by Django 5.0.7 on 2024-09-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subgrantees', '0019_remove_subgranteeprofile_current_projects_json_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subgranteeprofile',
            name='current_project_budget',
        ),
        migrations.RemoveField(
            model_name='subgranteeprofile',
            name='current_project_contact_info',
        ),
        migrations.RemoveField(
            model_name='subgranteeprofile',
            name='current_project_description',
        ),
        migrations.RemoveField(
            model_name='subgranteeprofile',
            name='current_project_donor',
        ),
        migrations.RemoveField(
            model_name='subgranteeprofile',
            name='current_project_timeframe',
        ),
        migrations.RemoveField(
            model_name='subgranteeprofile',
            name='past_project_budget',
        ),
        migrations.RemoveField(
            model_name='subgranteeprofile',
            name='past_project_contact_info',
        ),
        migrations.RemoveField(
            model_name='subgranteeprofile',
            name='past_project_name',
        ),
        migrations.RemoveField(
            model_name='subgranteeprofile',
            name='past_project_outcomes',
        ),
        migrations.RemoveField(
            model_name='subgranteeprofile',
            name='past_project_timeframe',
        ),
        migrations.AddField(
            model_name='subgranteeprofile',
            name='current_projects',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subgranteeprofile',
            name='past_projects',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
