# Generated by Django 5.0.7 on 2024-09-17 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subgrantees', '0020_remove_subgranteeprofile_current_project_budget_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subgranteeprofile',
            name='partnership_description',
        ),
        migrations.RemoveField(
            model_name='subgranteeprofile',
            name='partnership_name',
        ),
        migrations.RemoveField(
            model_name='subgranteeprofile',
            name='partnership_period',
        ),
        migrations.RemoveField(
            model_name='subgranteeprofile',
            name='subgrant_amount',
        ),
        migrations.RemoveField(
            model_name='subgranteeprofile',
            name='subgrant_description',
        ),
        migrations.RemoveField(
            model_name='subgranteeprofile',
            name='subgrant_donor',
        ),
        migrations.RemoveField(
            model_name='subgranteeprofile',
            name='subgrant_duration',
        ),
        migrations.AddField(
            model_name='subgranteeprofile',
            name='partnerships',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subgranteeprofile',
            name='subgrants',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
