# Generated by Django 5.0.7 on 2024-10-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subgrantees', '0021_remove_subgranteeprofile_partnership_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('head_offfice', models.CharField(max_length=255)),
                ('website', models.URLField()),
                ('year_of_establishment', models.IntegerField()),
                ('contact_info', models.JSONField()),
            ],
        ),
    ]
