# Generated by Django 5.0.7 on 2024-10-24 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subgrantees', '0022_bank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='head_offfice',
            new_name='head_office',
        ),
    ]
