# Generated by Django 5.0.7 on 2024-10-02 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_message_is_read'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-timestamp']},
        ),
    ]
