# Generated by Django 5.0.7 on 2024-10-02 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_alter_message_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['timestamp']},
        ),
    ]
