# Generated by Django 5.0.7 on 2024-08-07 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grants_management', '0001_initial'),
        ('subgrantees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='grantreport',
            name='subgrantee_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subgrantees.subgranteeprofile'),
        ),
        migrations.AddField(
            model_name='grantreview',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grants_management.grantapplication'),
        ),
        migrations.AddField(
            model_name='grantreview',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grant',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grants_management.granttype'),
        ),
        migrations.AddField(
            model_name='subsection',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grants_management.section'),
        ),
        migrations.AddField(
            model_name='defaultapplicationquestion',
            name='sub_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grants_management.subsection'),
        ),
    ]
