# Generated by Django 5.0.7 on 2024-08-11 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants_management', '0003_grant_is_open'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationquestion',
            name='default_question',
        ),
        migrations.RemoveField(
            model_name='applicationquestion',
            name='grant',
        ),
        migrations.AddField(
            model_name='defaultapplicationquestion',
            name='grant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grants_management.grant'),
        ),
        migrations.CreateModel(
            name='GrantSpecificQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_required', models.BooleanField(default=True)),
                ('question_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('checkbox', 'Checkbox')], default='text', max_length=10)),
                ('choices', models.JSONField(blank=True, null=True)),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grants_management.grant')),
            ],
        ),
        migrations.DeleteModel(
            name='ApplicantResponse',
        ),
        migrations.DeleteModel(
            name='ApplicationQuestion',
        ),
    ]
