# Generated by Django 5.0.7 on 2024-08-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants_management', '0005_grantapplicationresponses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultapplicationquestion',
            name='number_of_rows',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='defaultapplicationquestion',
            name='question_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('checkbox', 'Checkbox'), ('table', 'Table')], max_length=10),
        ),
    ]
