# Generated by Django 5.0.7 on 2024-08-12 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grants_management', '0009_alter_defaultapplicationquestion_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defaultapplicationquestion',
            name='section',
        ),
    ]
