# Generated by Django 5.0.7 on 2024-08-12 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants_management', '0010_remove_defaultapplicationquestion_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultapplicationquestion',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grants_management.section'),
        ),
    ]
