# Generated by Django 5.0.7 on 2024-08-12 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants_management', '0014_alter_grantapplication_subgrantee'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrantApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='media/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='grants_management.grantapplication')),
            ],
        ),
    ]
