# Generated by Django 5.0.7 on 2024-08-12 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grants_management', '0015_grantapplicationdocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grantapplicationdocument',
            name='application',
        ),
    ]
