# Generated by Django 5.0.7 on 2024-08-13 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grants_management', '0016_remove_grantapplicationdocument_application'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GrantApplicationDocument',
        ),
    ]
