# Generated by Django 5.0.7 on 2024-08-13 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants_management', '0018_grantapplicationdocument'),
        ('subgrantees', '0013_alter_subgranteeprofile_acronym'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grantapplication',
            name='subgrantee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application', to='subgrantees.subgranteeprofile'),
        ),
    ]
