# Generated by Django 5.0.7 on 2024-08-13 12:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grants_management', '0024_alter_grantapplication_subgrantee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GrantReview',
            new_name='GrantApplicationReview',
        ),
    ]
