# Generated by Django 5.0.7 on 2024-08-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants_management', '0025_rename_grantreview_grantapplicationreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grantapplicationreview',
            name='status',
        ),
        migrations.AddField(
            model_name='grantapplicationreview',
            name='action',
            field=models.CharField(choices=[('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=50),
        ),
    ]
