# Generated by Django 5.0.7 on 2024-08-14 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants_management', '0026_remove_grantapplicationreview_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grantapplicationreview',
            name='action',
        ),
        migrations.AddField(
            model_name='grantapplicationreview',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=50),
        ),
    ]
