# Generated by Django 5.0.7 on 2024-08-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants_management', '0028_transformedgrantapplicationdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transformedgrantapplicationdata',
            name='transformed_data',
            field=models.JSONField(default=dict),
        ),
    ]
