# Generated by Django 5.0.7 on 2024-08-15 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants_management', '0029_alter_transformedgrantapplicationdata_transformed_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grantapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete')], default='pending', max_length=100),
        ),
    ]
