# Generated by Django 5.0.7 on 2024-08-19 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants_management', '0030_alter_grantapplication_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grantapplicationdocument',
            name='application',
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='documents',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grants_management.grantapplicationdocument'),
        ),
        migrations.AddField(
            model_name='grantapplicationdocument',
            name='document_type',
            field=models.CharField(choices=[('proposal', 'Proposal'), ('budget', 'Budget'), ('other', 'Other')], default=True, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grantapplicationdocument',
            name='document',
            field=models.FileField(upload_to='application_docs/'),
        ),
    ]
