# Generated by Django 5.0.7 on 2024-08-19 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants_management', '0031_remove_grantapplicationdocument_application_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grantapplication',
            name='documents',
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='documents',
            field=models.ManyToManyField(blank=True, to='grants_management.grantapplicationdocument'),
        ),
    ]
