# Generated by Django 5.0.7 on 2024-08-19 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants_management', '0032_remove_grantapplication_documents_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grantapplication',
            name='documents',
        ),
        migrations.RemoveField(
            model_name='grantapplicationdocument',
            name='document_type',
        ),
        migrations.AddField(
            model_name='grantapplicationdocument',
            name='application',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='grants_management.grantapplication'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grantapplicationdocument',
            name='user',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grantapplicationdocument',
            name='document',
            field=models.FileField(upload_to='grant_applications/%Y/%m/%d/'),
        ),
    ]
