# Generated by Django 5.0.7 on 2024-08-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants_management', '0038_budgettotal_alter_grantaccount_budget_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgettotal',
            name='budget_total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
