# Generated by Django 5.0.7 on 2024-08-20 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants_management', '0039_alter_budgettotal_budget_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgettotal',
            name='budget_total',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
