# Generated by Django 5.0.7 on 2024-08-20 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants_management', '0040_alter_budgettotal_budget_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgettotal',
            name='grant',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='grants_management.grant'),
            preserve_default=False,
        ),
    ]
