# Generated by Django 5.0.7 on 2024-08-21 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants_management', '0041_budgettotal_grant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grantapplicationreview',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('negotiate', 'Negotiate')], default='pending', max_length=50),
        ),
    ]
