# Generated by Django 5.0.7 on 2024-08-21 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grants_management', '0043_grantapplicationdocument_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grantapplicationdocument',
            name='questions',
        ),
    ]
