# Generated by Django 5.0.7 on 2024-08-21 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants_management', '0045_grantapplicationdocument_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grantapplicationdocument',
            name='questions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='grants_management.filteredgrantapplicationresponse'),
        ),
    ]
