# Generated by Django 5.0.7 on 2024-08-21 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants_management', '0047_remove_grantapplicationdocument_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='grantapplicationdocument',
            name='documents',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='grantapplicationdocument',
            name='response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grants_management.filteredgrantapplicationresponse'),
        ),
    ]
