# Generated by Django 5.0.7 on 2024-08-21 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grants_management', '0048_grantapplicationdocument_documents_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grantapplicationdocument',
            name='response',
        ),
    ]
