# Generated by Django 5.0.7 on 2024-08-21 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grants_management', '0049_remove_grantapplicationdocument_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grantapplicationdocument',
            name='document',
        ),
    ]
