# Generated by Django 5.0.7 on 2024-08-22 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants_management', '0051_grantapplication_signed'),
        ('subgrantees', '0014_alter_subgranteeprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grant',
            name='district',
        ),
        migrations.AddField(
            model_name='grant',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subgrantees.district'),
        ),
    ]
