# Generated by Django 5.0.7 on 2024-08-22 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants_management', '0052_remove_grant_district_grant_district'),
        ('subgrantees', '0014_alter_subgranteeprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grant',
            name='district',
        ),
        migrations.AddField(
            model_name='grant',
            name='district',
            field=models.ManyToManyField(blank=True, to='subgrantees.district'),
        ),
    ]
