# Generated by Django 5.0.7 on 2024-08-23 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants_management', '0053_remove_grant_district_grant_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='grantaccount',
            old_name='account_name',
            new_name='account_holder',
        ),
        migrations.AlterField(
            model_name='budgettotal',
            name='budget_total',
            field=models.DecimalField(decimal_places=2, default=True, max_digits=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='FundingAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('allocation_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('reference_number', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grant_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='grants_management.grantaccount')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grants_management.budgetcategory')),
            ],
            options={
                'ordering': ['-allocation_date'],
            },
        ),
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fiscal_year', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grants_management.budgetcategory')),
                ('grant_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_items', to='grants_management.grantaccount')),
            ],
            options={
                'unique_together': {('grant_account', 'category', 'fiscal_year')},
            },
        ),
    ]
