# Generated by Django 5.0.7 on 2024-08-24 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grants_management', '0055_budgetcategory_user_budgetitem_user_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='budgetitem',
            unique_together=set(),
        ),
    ]
