# Generated by Django 5.0.7 on 2024-08-25 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants_management', '0056_alter_budgetitem_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundingallocation',
            name='source',
        ),
        migrations.AddField(
            model_name='fundingallocation',
            name='item',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='grants_management.budgetitem'),
            preserve_default=False,
        ),
    ]
