# Generated by Django 5.0.7 on 2024-08-25 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants_management', '0057_remove_fundingallocation_source_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundingallocation',
            name='item',
        ),
        migrations.AddField(
            model_name='fundingallocation',
            name='source',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='grants_management.budgetcategory'),
            preserve_default=False,
        ),
    ]
