# Generated by Django 5.0.7 on 2024-08-26 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grants_management', '0061_fundingallocation_total_allocated_grant_pkis_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FinancialReport',
        ),
    ]
