# Generated by Django 5.0.7 on 2024-08-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants_management', '0064_grant_reporting_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='reporting_time',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('biannually', 'Biannually'), ('annually', 'Annually'), ('weekly', 'Weekly')], max_length=20),
        ),
    ]
