# Generated by Django 5.0.7 on 2024-08-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants_management', '0065_alter_grant_reporting_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statusreport',
            old_name='created_at',
            new_name='report_date',
        ),
        migrations.RemoveField(
            model_name='statusreport',
            name='description',
        ),
        migrations.RemoveField(
            model_name='statusreport',
            name='user',
        ),
        migrations.AddField(
            model_name='statusreport',
            name='completed_pkis',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='statusreport',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='statusreport',
            name='progress_percentage',
            field=models.DecimalField(decimal_places=2, default=True, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='statusreport',
            name='status',
            field=models.CharField(choices=[('on_track', 'On Track'), ('at_risk', 'At Risk'), ('behind', 'Behind Schedule'), ('completed', 'Completed')], max_length=20),
        ),
    ]
