# Generated by Django 5.0.7 on 2024-08-26 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grants_management', '0066_rename_created_at_statusreport_report_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StatusReport',
            new_name='ProgressReport',
        ),
    ]
