# Generated by Django 5.0.7 on 2024-08-26 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grants_management', '0067_rename_statusreport_progressreport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grant',
            old_name='pkis',
            new_name='kpis',
        ),
        migrations.RemoveField(
            model_name='progressreport',
            name='notes',
        ),
    ]
