# Generated by Django 5.0.7 on 2024-08-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants_management', '0068_rename_pkis_grant_kpis_remove_progressreport_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='kpis',
            field=models.JSONField(default=dict),
        ),
    ]
