# Generated by Django 5.0.7 on 2024-08-27 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants_management', '0070_progressreport_last_updated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disbursement_date', models.DateField(auto_now_add=True)),
                ('grant_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disbursements', to='grants_management.grantaccount')),
            ],
        ),
    ]
