# Generated by Django 5.0.7 on 2024-08-27 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grants_management', '0071_disbursement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disbursement',
            old_name='amount',
            new_name='budget_balance',
        ),
        migrations.RenameField(
            model_name='disbursement',
            old_name='balance',
            new_name='disbursemnt_amount',
        ),
    ]
