# Generated by Django 5.0.7 on 2024-08-27 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grants_management', '0072_rename_amount_disbursement_budget_balance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disbursement',
            old_name='disbursemnt_amount',
            new_name='disbursement_amount',
        ),
    ]
