# Generated by Django 5.0.7 on 2024-08-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants_management', '0073_rename_disbursemnt_amount_disbursement_disbursement_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disbursement',
            name='budget_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
