# Generated by Django 5.0.7 on 2024-08-28 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants_management', '0074_alter_disbursement_budget_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='grantaccount',
            name='disbursed',
            field=models.CharField(choices=[('partially_disbursed', 'Partially Disbursed'), ('fully_disbursed', 'Fully Disbursed'), ('not_disbursed', 'Not_disbursed')], default='not', max_length=50),
        ),
    ]
