# Generated by Django 5.0.7 on 2024-08-28 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants_management', '0076_alter_grantaccount_disbursed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grantaccount',
            name='disbursed',
            field=models.CharField(choices=[('partially_disbursed', 'Partially Disbursed'), ('fully_disbursed', 'Fully Disbursed'), ('not_disbursed', 'Not Disbursed')], default='not_disbursed', max_length=50),
        ),
    ]
