# Generated by Django 5.0.7 on 2024-08-28 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants_management', '0077_alter_grantaccount_disbursed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='grantaccount',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('pending_closeout', 'Pending Closeout')], default='active', max_length=50),
        ),
        migrations.CreateModel(
            name='GrantCloseOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiated_date', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(choices=[('completed', 'Completed'), ('terminated', 'Terminated'), ('suspended', 'Suspended')], max_length=20)),
                ('lessons_learnt', models.TextField(blank=True, null=True)),
                ('best_practices', models.TextField(blank=True, null=True)),
                ('achievements', models.TextField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_closeouts', to=settings.AUTH_USER_MODEL)),
                ('grant_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='close_outs', to='grants_management.grantaccount')),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_closeouts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
