# Generated by Django 5.0.7 on 2024-08-28 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants_management', '0079_grantcloseoutdocuments_grantcloseoutreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='grantcloseout',
            name='completed_kpis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grants_management.progressreport'),
        ),
    ]
