# Generated by Django 5.0.7 on 2024-08-28 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants_management', '0080_grantcloseout_completed_kpis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grantcloseoutreview',
            name='closeout',
        ),
        migrations.AddField(
            model_name='grantcloseoutdocuments',
            name='user',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='closeout_documents', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grantcloseoutreview',
            name='closeout_document',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='grants_management.grantcloseoutdocuments'),
            preserve_default=False,
        ),
    ]
