# Generated by Django 5.0.7 on 2024-08-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants_management', '0083_modifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grantcloseoutdocuments',
            name='document',
            field=models.FileField(upload_to='closeout_documents/'),
        ),
    ]
