# Generated by Django 5.0.7 on 2024-08-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants_management', '0084_alter_grantcloseoutdocuments_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grantcloseoutdocuments',
            name='document',
            field=models.JSONField(default=dict),
        ),
    ]
