# Generated by Django 5.0.7 on 2024-08-29 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants_management', '0086_grantcloseoutdocuments_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grantcloseoutreview',
            name='closeout_document',
        ),
        migrations.AddField(
            model_name='grantcloseoutreview',
            name='closeout',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='grants_management.grantcloseout'),
            preserve_default=False,
        ),
    ]
