# Generated by Django 5.0.7 on 2024-08-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants_management', '0087_remove_grantcloseoutreview_closeout_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grantcloseoutdocuments',
            name='closeout',
        ),
        migrations.RemoveField(
            model_name='grantcloseoutreview',
            name='closeout',
        ),
        migrations.RemoveField(
            model_name='grantcloseoutdocuments',
            name='user',
        ),
        migrations.RemoveField(
            model_name='grantcloseoutreview',
            name='reviewer',
        ),
        migrations.RemoveField(
            model_name='modifications',
            name='grant_account',
        ),
        migrations.RemoveField(
            model_name='modifications',
            name='requested_by',
        ),
        migrations.RemoveField(
            model_name='modifications',
            name='reviewed_by',
        ),
        migrations.AlterField(
            model_name='grantaccount',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=50),
        ),
        migrations.DeleteModel(
            name='GrantCloseOut',
        ),
        migrations.DeleteModel(
            name='GrantCloseOutDocuments',
        ),
        migrations.DeleteModel(
            name='GrantCloseOutReview',
        ),
        migrations.DeleteModel(
            name='Modifications',
        ),
    ]
