# Generated by Django 5.0.7 on 2024-08-30 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants_management', '0091_requests_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='request',
            field=models.CharField(choices=[('grant_account', 'Grant Account'), ('budget_total', 'Budget Total'), ('budget_total_modification', 'Budget Total Modification'), ('disbursement', 'Disbursement'), ('closeout', 'Closeout'), ('modification', 'Modification'), ('document', 'Document'), ('review', 'Review'), ('grant_closeout', 'Grant Closeout')], max_length=50),
        ),
    ]
