# Generated by Django 5.0.7 on 2024-08-30 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grants_management', '0092_alter_requests_request'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Requests',
        ),
    ]
