# Generated by Django 5.0.7 on 2024-08-30 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants_management', '0093_delete_requests'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('grant_account', 'Grant Account'), ('budget_total', 'Budget Total'), ('budget_total_modification', 'Budget Total Modification'), ('disbursement', 'Disbursement'), ('closeout', 'Closeout'), ('modification', 'Modification'), ('document', 'Document'), ('review', 'Review'), ('grant_closeout', 'Grant Closeout')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grant_closeout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='grants_management.grantcloseout')),
                ('modifications', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='grants_management.modifications')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
