# Generated by Django 5.0.7 on 2024-08-30 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants_management', '0094_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grantaccount',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('pending_closeout', 'Pending Closeout')], default='active', max_length=50),
        ),
    ]
