# Generated by Django 5.0.7 on 2024-08-31 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants_management', '0095_alter_grantaccount_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grantapplicationdocument',
            name='documents',
            field=models.FileField(upload_to='grant_applications/'),
        ),
    ]
