# Generated by Django 5.0.7 on 2024-09-02 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants_management', '0096_alter_grantapplicationdocument_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='reporting_time',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually'), ('weekly', 'Weekly')], max_length=20),
        ),
    ]
