# Generated by Django 5.0.7 on 2024-09-02 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants_management', '0097_alter_grant_reporting_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grantcloseoutreview',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
