# Generated by Django 5.0.7 on 2024-09-02 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants_management', '0098_alter_grantcloseoutreview_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
