# Generated by Django 5.0.7 on 2024-09-02 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants_management', '0099_requests_reviewed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requests',
            name='reviewed',
        ),
        migrations.AddField(
            model_name='grantcloseout',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modifications',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
