# Generated by Django 5.0.7 on 2024-09-02 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grants_management', '0100_remove_requests_reviewed_grantcloseout_reviewed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grantcloseout',
            old_name='approved_by',
            new_name='reviewed_by',
        ),
    ]
