# Generated by Django 5.0.7 on 2024-09-02 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants_management', '0101_rename_approved_by_grantcloseout_reviewed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
