# Generated by Django 5.0.7 on 2024-09-02 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grants_management', '0102_requests_reviewed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grantcloseout',
            old_name='approved_date',
            new_name='review_date',
        ),
    ]
