# Generated by Django 5.0.7 on 2024-09-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants_management', '0103_rename_approved_date_grantcloseout_review_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressreport',
            name='reviewer_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
