# Generated by Django 5.0.7 on 2024-09-10 05:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants_management', '0104_progressreport_reviewer_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='request_type',
            field=models.CharField(choices=[('modification', 'Modification'), ('requirements', 'Requirements'), ('grant_closeout', 'Grant Closeout')], max_length=50),
        ),
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('items', models.JSONField()),
                ('grant_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='grants_management.grantaccount')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_requirements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Requirements',
            },
        ),
    ]
