# Generated by Django 5.0.7 on 2024-09-10 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants_management', '0105_alter_requests_request_type_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='requirements',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='grants_management.requirements'),
        ),
    ]
