# Generated by Django 5.0.7 on 2024-09-10 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants_management', '0107_requestreview_delete_grantcloseoutreview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='modifications',
            old_name='reviewed_date',
            new_name='review_date',
        ),
        migrations.AddField(
            model_name='requirements',
            name='review_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requirements',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requirements',
            name='reviewed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requirements', to=settings.AUTH_USER_MODEL),
        ),
    ]
