# Generated by Django 5.0.7 on 2024-09-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants_management', '0109_extensions_requests_extensions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='request_type',
            field=models.CharField(choices=[('modification', 'Modification'), ('requirements', 'Requirements'), ('grant_closeout', 'Grant Closeout'), ('extension', 'Extension')], max_length=50),
        ),
    ]
