# Generated by Django 5.0.7 on 2024-09-11 08:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants_management', '0112_financialreport_last_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grant',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
