# Generated by Django 5.0.7 on 2024-09-17 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants_management', '0113_grant_created_grant_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='number_of_awards',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
