# Generated by Django 5.0.7 on 2024-09-18 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants_management', '0114_grant_number_of_awards'),
    ]

    operations = [
        migrations.AddField(
            model_name='grantapplicationreview',
            name='upload',
            field=models.FileField(default=True, upload_to='grant_applications_review/'),
            preserve_default=False,
        ),
    ]
