# Generated by Django 5.0.7 on 2024-09-18 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grants_management', '0115_grantapplicationreview_upload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grantapplicationreview',
            old_name='upload',
            new_name='uploads',
        ),
    ]
