# Generated by Django 5.0.7 on 2024-09-18 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grants_management', '0116_rename_upload_grantapplicationreview_uploads'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grantapplicationreview',
            name='uploads',
        ),
    ]
