# Generated by Django 5.0.7 on 2024-09-18 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants_management', '0117_remove_grantapplicationreview_uploads'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrantApplicationReviewDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='grant_application_reviews/')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grants_management.grantapplicationreview')),
            ],
        ),
    ]
