# Generated by Django 5.0.7 on 2024-09-18 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grants_management', '0118_grantapplicationreviewdocument'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grantapplicationreviewdocument',
            old_name='document',
            new_name='uploads',
        ),
    ]
