# Generated by Django 5.0.7 on 2024-09-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants_management', '0119_rename_document_grantapplicationreviewdocument_uploads'),
    ]

    operations = [
        migrations.AddField(
            model_name='grantapplication',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
