# Generated by Django 5.0.7 on 2024-09-20 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants_management', '0120_grantapplication_reviewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grantaccount',
            name='current_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
