# Generated by Django 5.0.7 on 2024-09-26 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants_management', '0121_alter_grantaccount_current_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='grantapplication',
            name='last_response_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='last_review_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
