# Generated by Django 5.0.7 on 2024-09-26 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants_management', '0122_grantapplication_last_response_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grantapplication',
            name='status',
            field=models.CharField(choices=[('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('negotiation', 'Negotiation')], default='under_review', max_length=100),
        ),
    ]
