# Generated by Django 5.0.7 on 2024-10-22 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants_management', '0125_alter_grantapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirements',
            name='docs',
            field=models.FileField(blank=True, null=True, upload_to='requirements_docs/'),
        ),
    ]
