# Generated by Django 5.0.7 on 2024-08-16 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants_management', '0030_alter_grantapplication_status'),
        ('notifications', '0001_initial'),
        ('subgrantees', '0013_alter_subgranteeprofile_acronym'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grants_management.grantapplication'),
        ),
        migrations.AddField(
            model_name='notification',
            name='grant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grants_management.grant'),
        ),
        migrations.AddField(
            model_name='notification',
            name='subgrantee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subgrantees.subgranteeprofile'),
        ),
    ]
