# Generated by Django 5.0.7 on 2024-08-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_application_notification_grant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_category',
            field=models.CharField(choices=[('new_grant', 'New Grant'), ('grant_applicatoin', 'Grant Application'), ('grant_review', 'Grant Review'), ('new_subgrantee', 'New Subgrantee')], default=True, max_length=20),
            preserve_default=False,
        ),
    ]
