# Generated by Django 5.0.7 on 2024-08-16 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants_management', '0030_alter_grantapplication_status'),
        ('notifications', '0003_notification_notification_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grants_management.grantapplicationreview'),
        ),
    ]
