# Generated by Django 5.0.7 on 2024-08-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_category',
            field=models.CharField(choices=[('new_grant', 'New Grant'), ('grant_applicatoin', 'Grant Application'), ('grant_review', 'Grant Review'), ('new_subgrantee', 'New Subgrantee'), ('grant_submisson', 'Grant Submission')], max_length=20),
        ),
    ]
