# Generated by Django 5.0.7 on 2024-08-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_alter_notification_notification_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_category',
            field=models.CharField(choices=[('new_grant', 'New Grant'), ('grant_applicatoin', 'Grant Application'), ('grant_review', 'Grant Review'), ('new_subgrantee', 'New Subgrantee'), ('grant_submisson', 'Grant Submission'), ('status_report_due', 'Status Report Due'), ('status_report_submitted', 'Status Report Submitted'), ('status_report_reviewed', 'Status Report Reviewed'), ('disbursement_received', 'Disbursement Received')], max_length=30),
        ),
    ]
