# Generated by Django 5.0.7 on 2024-09-04 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants_management', '0103_rename_approved_date_grantcloseout_review_date'),
        ('notifications', '0012_notificationuser'),
        ('subgrantees', '0016_alter_subgranteeprofile_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.AddField(
            model_name='notification',
            name='users',
            field=models.ManyToManyField(related_name='notifications', through='notifications.NotificationUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grants_management.grantapplication'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='grant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grants_management.grant'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_category',
            field=models.CharField(choices=[('new_grant', 'New Grant'), ('grant_application', 'Grant Application'), ('grant_review', 'Grant Review'), ('new_subgrantee', 'New Subgrantee'), ('grant_submission', 'Grant Submission'), ('status_report_due', 'Status Report Due'), ('status_report_submitted', 'Status Report Submitted'), ('status_report_reviewed', 'Status Report Reviewed'), ('disbursement_received', 'Disbursement Received'), ('grant_closeout', 'Grant Closeout'), ('grant_closeout_review', 'Grant Closeout Review')], max_length=30),
        ),
        migrations.AlterField(
            model_name='notification',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grants_management.grantapplicationreview'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='subgrantee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subgrantees.subgranteeprofile'),
        ),
    ]
