# Generated by Django 5.0.7 on 2024-09-04 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants_management', '0103_rename_approved_date_grantcloseout_review_date'),
        ('notifications', '0013_remove_notification_is_read_remove_notification_user_and_more'),
        ('subgrantees', '0016_alter_subgranteeprofile_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='users',
        ),
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grants_management.grantapplication'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='grant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grants_management.grant'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_category',
            field=models.CharField(choices=[('new_grant', 'New Grant'), ('grant_applicatoin', 'Grant Application'), ('grant_review', 'Grant Review'), ('new_subgrantee', 'New Subgrantee'), ('grant_submisson', 'Grant Submission'), ('status_report_due', 'Status Report Due'), ('status_report_submitted', 'Status Report Submitted'), ('status_report_reviewed', 'Status Report Reviewed'), ('disbursement_received', 'Disbursement Received'), ('grant_closeout', 'Grant Closeout'), ('grant_closeout_review', 'Grant Closeout Review')], max_length=30),
        ),
        migrations.AlterField(
            model_name='notification',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grants_management.grantapplicationreview'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='subgrantee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subgrantees.subgranteeprofile'),
        ),
        migrations.DeleteModel(
            name='NotificationUser',
        ),
    ]
