# Generated by Django 5.0.7 on 2024-09-04 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0015_remove_notification_user_notification_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='status',
        ),
    ]
