# Generated by Django 5.0.7 on 2024-10-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0025_notification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='review_recommendation',
            field=models.CharField(blank=True, choices=[('approve', 'Approve'), ('decline', 'Decline'), ('negotiate', 'Negotiate')], max_length=20, null=True),
        ),
    ]
