# Generated by Django 5.0.7 on 2024-10-04 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants_management', '0125_alter_grantapplication_status'),
        ('notifications', '0028_alter_notification_notification_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='progress_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grants_management.progressreport'),
        ),
    ]
