# Generated by Django 5.0.7 on 2024-10-04 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_alter_message_options'),
        ('notifications', '0029_notification_progress_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='chats',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chats.message'),
        ),
    ]
